spring:
#  redis:
#    host: 127.0.0.1
#      port: 6380
#      password:
#      database: 0
#      lettuce:
#        pool:
#          max-active: 32
#          max-wait: 300ms
#          max-idle: 16
#          min-idle: 8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
server:
  port: 8080
